apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - host: localhost
    http:
        paths:
        - path: /http
          backend:
            serviceName: http-deployment
            servicePort: 8080

