apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-deployment1
spec:
    replicas: 2
    selector:
      matchLabels:
        app: http
    template:
      metadata:
        labels:
          app: http
      spec:
        containers:
        - name: call
          image: 192.168.56.3:5000/my-http1
          imagePullPolicy: Always
          command: [ "/main" ]
          ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: http-deployment1
spec:
  ports:
  - port: 8080
    nodePort: 30699
    protocol: TCP
    targetPort: 8080
  selector:
    app: http
  type: NodePort
status:
  loadBalancer: {}
