apiVersion: batch/v1
kind: Job
metadata:
  name: create-database
spec:
    template:
      spec:
        containers:
        - name: call
          image: createdatabase
          imagePullPolicy: IfNotPresent
          command: [ "/main" ]
          env:
          - name: CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: connection-string
                key: connection_string
        restartPolicy: Never
    backoffLimit: 4      
