apiVersion: v1
kind: Service
metadata:
    name: "laurijssen-a966"
    labels:
        app: "laurijssen-a966"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "laurijssen-a966"