apiVersion: apps/v1
kind: Deployment
metadata:
  name: location
spec:
    replicas: 2
    selector:
      matchLabels:
        app: location
    template:
      metadata:
        labels:
          app: location
      spec:
        containers:
        - name: location
          image: location-service
          imagePullPolicy: IfNotPresent
          command: [ "/main" ]
          ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: location
spec:
  ports:
  - port: 8080
    nodePort: 30700
    protocol: TCP
    targetPort: 8080
  selector:
    app: location
  type: NodePort
status:
  loadBalancer: {}
